/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as DrivesRouteImport } from './routes/drives'
import { Route as HospitalRegisterRouteImport } from './routes/hospital-register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as DonorDashboardRouteImport } from './routes/donor.dashboard'
import { Route as DonorDocumentsRouteImport } from './routes/donor.documents'
import { Route as DonorHospitalsRouteImport } from './routes/donor.hospitals'
import { Route as HospitalDashboardRouteImport } from './routes/hospital.dashboard'
import { Route as HospitalDrivesRouteImport } from './routes/hospital.drives'
import { Route as HospitalRequestMatchesRouteImport } from './routes/hospital.request-matches'
import { Route as HospitalStockRouteImport } from './routes/hospital.stock'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsNewRouteImport } from './routes/requests.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivesRoute = DrivesRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRegisterRoute = HospitalRegisterRouteImport.update({
  id: '/hospital-register',
  path: '/hospital-register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorDashboardRoute = DonorDashboardRouteImport.update({
  id: '/donor/dashboard',
  path: '/donor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorDocumentsRoute = DonorDocumentsRouteImport.update({
  id: '/donor/documents',
  path: '/donor/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorHospitalsRoute = DonorHospitalsRouteImport.update({
  id: '/donor/hospitals',
  path: '/donor/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDashboardRoute = HospitalDashboardRouteImport.update({
  id: '/hospital/dashboard',
  path: '/hospital/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDrivesRoute = HospitalDrivesRouteImport.update({
  id: '/hospital/drives',
  path: '/hospital/drives',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRequestMatchesRoute = HospitalRequestMatchesRouteImport.update({
  id: '/hospital/request-matches',
  path: '/hospital/request-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalStockRoute = HospitalStockRouteImport.update({
  id: '/hospital/stock',
  path: '/hospital/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donors': typeof DonorsRoute
  '/drives': typeof DrivesRoute
  '/hospital-register': typeof HospitalRegisterRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/network': typeof NetworkRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/donor/dashboard': typeof DonorDashboardRoute
  '/donor/documents': typeof DonorDocumentsRoute
  '/donor/hospitals': typeof DonorHospitalsRoute
  '/hospital/dashboard': typeof HospitalDashboardRoute
  '/hospital/drives': typeof HospitalDrivesRoute
  '/hospital/request-matches': typeof HospitalRequestMatchesRoute
  '/hospital/stock': typeof HospitalStockRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donors': typeof DonorsRoute
  '/drives': typeof DrivesRoute
  '/hospital-register': typeof HospitalRegisterRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/network': typeof NetworkRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/donor/dashboard': typeof DonorDashboardRoute
  '/donor/documents': typeof DonorDocumentsRoute
  '/donor/hospitals': typeof DonorHospitalsRoute
  '/hospital/dashboard': typeof HospitalDashboardRoute
  '/hospital/drives': typeof HospitalDrivesRoute
  '/hospital/request-matches': typeof HospitalRequestMatchesRoute
  '/hospital/stock': typeof HospitalStockRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests': typeof RequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donors': typeof DonorsRoute
  '/drives': typeof DrivesRoute
  '/hospital-register': typeof HospitalRegisterRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/network': typeof NetworkRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/donor/dashboard': typeof DonorDashboardRoute
  '/donor/documents': typeof DonorDocumentsRoute
  '/donor/hospitals': typeof DonorHospitalsRoute
  '/hospital/dashboard': typeof HospitalDashboardRoute
  '/hospital/drives': typeof HospitalDrivesRoute
  '/hospital/request-matches': typeof HospitalRequestMatchesRoute
  '/hospital/stock': typeof HospitalStockRoute
  '/requests/new': typeof RequestsNewRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/donors'
    | '/drives'
    | '/hospital-register'
    | '/login'
    | '/matches'
    | '/network'
    | '/register'
    | '/admin/dashboard'
    | '/donor/dashboard'
    | '/donor/documents'
    | '/donor/hospitals'
    | '/hospital/dashboard'
    | '/hospital/drives'
    | '/hospital/request-matches'
    | '/hospital/stock'
    | '/requests/new'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/donors'
    | '/drives'
    | '/hospital-register'
    | '/login'
    | '/matches'
    | '/network'
    | '/register'
    | '/admin/dashboard'
    | '/donor/dashboard'
    | '/donor/documents'
    | '/donor/hospitals'
    | '/hospital/dashboard'
    | '/hospital/drives'
    | '/hospital/request-matches'
    | '/hospital/stock'
    | '/requests/new'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/donors'
    | '/drives'
    | '/hospital-register'
    | '/login'
    | '/matches'
    | '/network'
    | '/register'
    | '/admin/dashboard'
    | '/donor/dashboard'
    | '/donor/documents'
    | '/donor/hospitals'
    | '/hospital/dashboard'
    | '/hospital/drives'
    | '/hospital/request-matches'
    | '/hospital/stock'
    | '/requests/new'
    | '/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonorsRoute: typeof DonorsRoute
  DrivesRoute: typeof DrivesRoute
  HospitalRegisterRoute: typeof HospitalRegisterRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  NetworkRoute: typeof NetworkRoute
  RegisterRoute: typeof RegisterRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  DonorDashboardRoute: typeof DonorDashboardRoute
  DonorDocumentsRoute: typeof DonorDocumentsRoute
  DonorHospitalsRoute: typeof DonorHospitalsRoute
  HospitalDashboardRoute: typeof HospitalDashboardRoute
  HospitalDrivesRoute: typeof HospitalDrivesRoute
  HospitalRequestMatchesRoute: typeof HospitalRequestMatchesRoute
  HospitalStockRoute: typeof HospitalStockRoute
  RequestsNewRoute: typeof RequestsNewRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drives': {
      id: '/drives'
      path: '/drives'
      fullPath: '/drives'
      preLoaderRoute: typeof DrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-register': {
      id: '/hospital-register'
      path: '/hospital-register'
      fullPath: '/hospital-register'
      preLoaderRoute: typeof HospitalRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/dashboard': {
      id: '/donor/dashboard'
      path: '/donor/dashboard'
      fullPath: '/donor/dashboard'
      preLoaderRoute: typeof DonorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/documents': {
      id: '/donor/documents'
      path: '/donor/documents'
      fullPath: '/donor/documents'
      preLoaderRoute: typeof DonorDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/hospitals': {
      id: '/donor/hospitals'
      path: '/donor/hospitals'
      fullPath: '/donor/hospitals'
      preLoaderRoute: typeof DonorHospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/dashboard': {
      id: '/hospital/dashboard'
      path: '/hospital/dashboard'
      fullPath: '/hospital/dashboard'
      preLoaderRoute: typeof HospitalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/drives': {
      id: '/hospital/drives'
      path: '/hospital/drives'
      fullPath: '/hospital/drives'
      preLoaderRoute: typeof HospitalDrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/request-matches': {
      id: '/hospital/request-matches'
      path: '/hospital/request-matches'
      fullPath: '/hospital/request-matches'
      preLoaderRoute: typeof HospitalRequestMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/stock': {
      id: '/hospital/stock'
      path: '/hospital/stock'
      fullPath: '/hospital/stock'
      preLoaderRoute: typeof HospitalStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonorsRoute: DonorsRoute,
  DrivesRoute: DrivesRoute,
  HospitalRegisterRoute: HospitalRegisterRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  NetworkRoute: NetworkRoute,
  RegisterRoute: RegisterRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  DonorDashboardRoute: DonorDashboardRoute,
  DonorDocumentsRoute: DonorDocumentsRoute,
  DonorHospitalsRoute: DonorHospitalsRoute,
  HospitalDashboardRoute: HospitalDashboardRoute,
  HospitalDrivesRoute: HospitalDrivesRoute,
  HospitalRequestMatchesRoute: HospitalRequestMatchesRoute,
  HospitalStockRoute: HospitalStockRoute,
  RequestsNewRoute: RequestsNewRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
